# Generated by Django 4.0.1 on 2022-12-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='date_received',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
