# Generated by Django 4.0.1 on 2022-12-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('farm_name', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=700)),
                ('contact', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('desc', models.CharField(blank=True, max_length=700, null=True)),
                ('sku', models.CharField(blank=True, max_length=20, null=True)),
                ('brand', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(upload_to='product_images')),
                ('cat', models.CharField(blank=True, max_length=20, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('cart_price', models.IntegerField(blank=True, default=0, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
