# Generated by Django 4.0.1 on 2022-12-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='p5.jpg', null=True, upload_to=''),
        ),
    ]
