# Generated by Django 4.0.1 on 2022-12-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_categorie_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='manager',
        ),
    ]
